server:
  port: 8081

spring:
  mvc:
    static-path-pattern: /**
  # mysql数据库
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://106.75.126.136:3306/mall?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1qaz2wsx!@#?

mybatis:
  #  MyBatis扫描实体类
  type-aliases-package: com.mall.api.common.**.entity
  #  MyBatis Mapper 路径
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
