server:
  port: 8083
  servlet:
    session:
      cookie:
        name: portal
oauth-server-url: http://localhost:8081
security:
  oauth2:
    client:
      client-id: client
      client-secret: admin
      user-authorization-uri: ${oauth-server-url}/oauth/authorize
      access-token-uri: ${oauth-server-url}/oauth/token
    resource:
      jwt:
        key-uri: ${oauth-server-url}/oauth/token_key
        key-value: token_key
#rabbitmq配置
spring:
  rabbitmq:
    host: 124.70.188.60
    port: 5672
    username: op
    password: op
    virtual-host: /op
