server:
  port: 8085
  servlet:
    context-path: /mall

spring:
  # 发送邮件配置
  mail:
    host: smtp.qq.com # 配置 smtp 服务器地址
    port: 587 # smtp 服务器的端口
    username: 4284857@qq.com # 配置邮箱用户名(你的邮箱地址)
    password: hqreuaafsvfmbiei # 配置申请到的授权码(刚让复制的授权码)
    default-encoding: UTF-8 # 配置邮件编码
    properties:
      mail:
        smtp:
          socketFactoryClass: javax.net.ssl.SSLSocketFactory # 配饰 SSL 加密工厂
        debug: true
    from: 4284857@qq.com # 发送方邮件，配在yml中可方便更改
    subject: java开发工作室验证码
  #数据库配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_mail?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
